name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: 'Build and Publish'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn build-cjs
      - run: "echo '{\"type\": \"commonjs\"}' > ./dist/cjs/package.json"
      - run: yarn build-esm
      - run: "echo '{\"type\": \"module\"}' > ./dist/esm/package.json"
      - run: yarn publish --new-version "$(echo "${{ github.ref_name }}" | cut -d'v' -f2)" --no-git-tag-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
